# Generated by Django 4.1.7 on 2023-02-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="Doctor first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="Doctor last name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=120, verbose_name="Email address"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Doctor phone number"
                    ),
                ),
                ("hospital", models.CharField(max_length=255, verbose_name="hospital")),
                (
                    "licence_number",
                    models.CharField(
                        max_length=10, verbose_name="Proffesional_Licence_no"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="School name")),
                (
                    "address",
                    models.CharField(max_length=120, verbose_name="School address"),
                ),
                (
                    "email",
                    models.EmailField(max_length=120, verbose_name="School email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="School phone number"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="age")),
                ("height", models.IntegerField(verbose_name="height")),
                ("weight", models.IntegerField(verbose_name="weight")),
                ("BG", models.CharField(max_length=120, verbose_name="Blood Group")),
                (
                    "BP",
                    models.CharField(
                        max_length=10, verbose_name="Blood Pressure Level"
                    ),
                ),
                ("BMI", models.IntegerField(verbose_name="Body Mass Index")),
                (
                    "mother_name",
                    models.CharField(max_length=120, verbose_name="Mother's Name "),
                ),
                (
                    "mother_phone",
                    models.CharField(max_length=13, verbose_name="Mother's Contact"),
                ),
                (
                    "father_name",
                    models.CharField(max_length=120, verbose_name="Father's Name"),
                ),
                (
                    "father_phone",
                    models.CharField(max_length=13, verbose_name="Father's Contact"),
                ),
                (
                    "Allergies",
                    models.TextField(
                        default=None, max_length=255, verbose_name="Allergies"
                    ),
                ),
                (
                    "vaccines_received",
                    models.TextField(max_length=100, verbose_name="Vaccines received"),
                ),
                (
                    "hiv_status",
                    models.CharField(max_length=10, verbose_name="HIV/AIDS"),
                ),
                (
                    "symptoms",
                    models.TextField(
                        verbose_name="Sypmtoms at the time of hospital visit"
                    ),
                ),
                (
                    "tests",
                    models.TextField(verbose_name="Clinical Results and Tests done"),
                ),
                ("diagnosis", models.TextField(verbose_name="Doctor's diagnosis")),
                (
                    "hospital",
                    models.CharField(max_length=255, verbose_name="Hospital Name"),
                ),
                (
                    "prescription",
                    models.TextField(verbose_name="Treatment prescription"),
                ),
                ("progress_notes", models.TextField(verbose_name="Progress notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date of records"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="Patient first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="Patient last name"),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "patient_number",
                    models.CharField(
                        default="", max_length=120, verbose_name="Patient number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=120, verbose_name="Patient email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Patient phone number"
                    ),
                ),
                (
                    "patient_status_on_admission",
                    models.CharField(
                        default="Critical condition",
                        max_length=120,
                        verbose_name="patient status",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.doctor",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.school",
                    ),
                ),
            ],
        ),
    ]
