# Generated by Django 4.1.7 on 2023-02-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="School name")),
                (
                    "address",
                    models.CharField(max_length=120, verbose_name="School address"),
                ),
                (
                    "email",
                    models.EmailField(max_length=120, verbose_name="School email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="School phone number"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.hospital",
            ),
        ),
    ]
