# Generated by Django 4.1.7 on 2023-02-26 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0002_hospital_remove_doctor_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="licence_number",
            field=models.CharField(
                max_length=10, verbose_name="Proffesional Licence Number"
            ),
        ),
    ]
