# Generated by Django 4.1.7 on 2023-02-26 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0003_doctor_user_alter_doctor_licence_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="registered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
