# Generated by Django 4.1.7 on 2023-02-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_doctor_hospital_alter_patient_registered_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_number",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="Patient number"
            ),
        ),
    ]
