# Generated by Django 4.1.7 on 2023-02-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_patient_user_alter_patient_registered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
            preserve_default=False,
        ),
    ]
