# Generated by Django 4.1.7 on 2023-02-26 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0007_patientrecord_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientrecord",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="patientrecord",
            name="hiv_status",
            field=models.CharField(
                choices=[
                    ("negative", "Negative"),
                    ("positive", "Positive"),
                    ("na", "N/A"),
                ],
                max_length=10,
                verbose_name="HIV/AIDS",
            ),
        ),
    ]
